### ISSUE TITLE
i have this error :    ERROR Error: Uncaught (in promise): Error: The pipe 'async' could not be found!

### ISSUE THREAD

**Issue by chanez2020amk** [VadimDez/ngx-order-pipe#109]
### this is my  templet html 
`
                            <tr
                                *ngFor="let command of commande$ | async">

                                <td>  {{command.payload.val().dateCommande}} </td>
                               </tr>`
### the service  file 
` getcommandesList() {
    return this.db.list(this.dbPath).snapshotChanges();
  }`

### the typeScripte file i inserte this instruction in the constroctor

`   this.commande$=this.comService.getcommandesList();`

**Comment by VadimDez** [comment]
It seems to me that this has nothing to do with the `ngx-order-pipe` library
