### ISSUE TITLE
Build Error after Latest Update

### ISSUE THREAD

**Issue by tcrite** [VadimDez/ngx-order-pipe#110]
Hi, since the latest update I've started getting the error below:

Error: getInternalNameOfClass() called on a non-ES5 class: expected OrderPipe to have an inner class declaration

Thanks in advance for any assistance.

**Comment by wvankuipers** [comment]
Seems to be caused by the upgrade of `ng-packagr`:

From the changelog of version 10:
>If you are not using Angular CLI to build your application or library, and you need to be able to build es5 artifacts, then you will need to downlevel the distributed Angular code to es5 on your own.

Let me check if I can create a PR for this.

**Comment by wvankuipers** [comment]
I could not fix (or rather test) it for the current version as I don't use Angular 8 in my projects so I made a PR based on the angular 10 upgrade branche.

**Comment by wvankuipers** [comment]
@VadimDez Any chance this can be merged and a release of the Angular 10 version will be done? 😇

**Comment by VadimDez** [comment]
What's the point to make it es5? Is it just because of IE11?

**Comment by wvankuipers** [comment]
Yes IE 11 support :(
