### ISSUE TITLE
Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by ravi198715** [VadimDez/ngx-order-pipe#13]
I tried to run this pipe and i am getting this errror
Unexpected module 'Ng2OrderModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

I looked at the files and it seems its missing @pipe annotation.
I am running it on angular 4.0.0

**Comment by Saporules** [comment]
I have the same problem but instead of  'Ng2OrderModule' is 'OrderModule' as the Reademe File shows.

**Comment by VadimDez** [comment]
Do you still have this issue ?

**Comment by erperejildo** [comment]
Same here

**Comment by erperejildo** [comment]
installed today so latest one

**Comment by gkamtzir** [comment]
I've got the same problem with the latest version.

**Comment by VadimDez** [comment]
Could someone describe how to reproduce this issue?

**Comment by sorxrob** [comment]
I bet they're getting this problem in latest version of Ionic...

**Comment by gkamtzir** [comment]
Ionic version: 3.12.0
I installed the package from npm and then imported it in my app.module.ts. I placed the pipe in the template of one my Components and during compilation this particular error showed up.

**Comment by sorxrob** [comment]
I fixed it by following [this tutorial ](https://youtu.be/h4qrhJFeudA).

**Comment by nyn0x** [comment]
This error appears when I put OrderModule in `@NgModule ({declarations: ...}) `haha. Obviously you have to put it in `@NgModule ({imports: ...})` ! 
:D

**Comment by erperejildo** [comment]
watched the video but didn't see any fix @sorxrob

**Comment by VadimDez** [comment]
@erperejildo do you still have this error?

**Comment by erperejildo** [comment]
No, juts https://github.com/VadimDez/ngx-order-pipe/issues/47
