### ISSUE TITLE
Multi Ordering?

### ISSUE THREAD

**Issue by mstfsnkl** [VadimDez/ngx-order-pipe#14]
Hello. Thanks for the pipe. It's been really usefull to me. 

I want to ask if it is possible to order according to multiple values in order. For example first with Ages of people then the alphabetical order? If not, can you make it so? :)

**Comment by nosTa1337** [comment]
+1

**Comment by cgrall4cloud** [comment]
+1

**Comment by vfert** [comment]
+1

**Comment by vaynard** [comment]
+1

**Comment by RedStarThrower** [comment]
+1

**Comment by leoruhland** [comment]
I was also needing this functionality and in fact I discovered that it is much simpler than I imagined. Using multiple pipes:

```
{{ listOfObjects | orderBy:'age' | orderBy:'name' }}
```

**Comment by berkakkerman** [comment]
+1

**Comment by Emkacf** [comment]
+1

**Comment by rev87** [comment]
+1

**Comment by mubasshir** [comment]
+1

**Comment by gustavojnt** [comment]
+1

**Comment by mubasshir** [comment]
any plans to work on it?

**Comment by wcy327417110** [comment]
+1

**Comment by VadimDez** [comment]
Released in `2.0.1`
https://github.com/VadimDez/ngx-order-pipe/releases/tag/2.0.1

**Comment by mubasshir** [comment]
awesome thanks.

**Comment by nosTa1337** [comment]
I have one question. Do you support reverse ordering for arrays?

e.g. ['value1' , true, 'value2', false] ?

**Comment by mixalistzikas** [comment]
If we sort with 2 different fields... can we set different "Reverse sorting order" for each field??

**Comment by devendramahajan** [comment]
Any update on ordering multiple fields in reverse order?

**Comment by paulsonantajo** [comment]
It is not working in the build version.
