### ISSUE TITLE
Cannot find module @angular/core

### ISSUE THREAD

**Issue by rolandoldengarm** [VadimDez/ngx-order-pipe#18]
Adding it to an Angular CLI project, then importing in my shared module.

Building the project returns in:

```
ERROR in C:/projects/client/node_modules/ngx-order-pipe/dist/src/ngx-order.pipe.d.ts (1,31): Cannot find module '@angular/core'.
```
I'm on Angular 4.

**Comment by VadimDez** [comment]
How is that possible ?
Are you importing `OrderModule` like this ?
```ts
import { OrderModule } from 'ngx-order-pipe';
```

**Comment by rolandoldengarm** [comment]
Yes, exactly like that. Very weird, never seen that issue before with other modules...

**Comment by teraldo79** [comment]
Same issue here. First i tried the NG2OrderModule, due to an old Stack post that i saw. then tried the ngx version. both had the same error that the module couldnt find @angular/core.

**Comment by bayanAbuawad** [comment]
Same issue here
