### ISSUE TITLE
Refresh orderBy after *ngFor is updated?

### ISSUE THREAD

**Issue by FahadAlbukhari** [VadimDez/ngx-order-pipe#23]
How to refresh the order automatic on any changes of the *ngFor?

**Comment by VadimDez** [comment]
`orderBy` is applied right after array in `*ngFor` is changed

**Comment by kkamalesh** [comment]
Hi i used the below code after installing the Ng2OrderModule.but its not ordering the list by the type field.what i am doing wrong please let me know.
<div *ngFor="let favorite of favoriteReports | orderBy: 'favorite.type'" title="{{favorite.title}}" class="row-striped">
  <a [routerLink]="['/report/documentList',{reportId:favorite.id}]"
     *ngIf="favorite.type=='Report'" (click)="selectFavorite(favorite,$event)">
    <i class="fa fa-file-text"></i>&nbsp; {{favorite.title}}</a>
  <a [routerLink]="['/report/', favorite.folderPathId]" *ngIf="favorite.type!='Report'"
     (click)="selectFavorite(favorite,$event)">
    <i class="fa fa-folder-open"></i>&nbsp; {{favorite.title}}</a>
</div>

**Comment by kkamalesh** [comment]
<div *ngFor="let favorite of favoriteReports | orderBy: 'favorite.type'" title="{{favorite.title}}" class="row-striped">
  <a [routerLink]="['/report/documentList',{reportId:favorite.id}]"
     *ngIf="favorite.type=='Report'" (click)="selectFavorite(favorite,$event)">
    <i class="fa fa-file-text"></i>&nbsp; {{favorite.title}}</a>
  <a [routerLink]="['/report/', favorite.folderPathId]" *ngIf="favorite.type!='Report'"
     (click)="selectFavorite(favorite,$event)">
    <i class="fa fa-folder-open"></i>&nbsp; {{favorite.title}}</a>
</div>

**Comment by VadimDez** [comment]
Try to install `ngx-order-pipe` (see installation and usage in the [documentation](https://github.com/VadimDez/ngx-order-pipe/blob/master/README.md)) instead of `ng2-order-pipe`.

**Comment by DigitalMystery** [comment]
The refresh is not working for me either.

` *ngFor="let myItem of myObject.myItems | orderBy: 'itemOrder'"`

itemOrder is a property off myItem.  I had to add the ticks ' for it to work as well which I did not see in the example.

**Comment by JavanXD** [comment]
@VadimDez 
The refresh is not working for me either.
`<li *ngFor="let address of addresses | orderBy:'validFrom':true; let i = index">`
validFrom is a prop of address and the type is Date.
After adding an `address` to `addresses` and also changing the value of a `validFrom` the list does not reorder as expected.

**Comment by ESimmonds** [comment]
works if the pipe is stateful 
```
@Pipe({
  name: 'orderBy',
  pure: false
})
```

**Comment by VadimDez** [comment]
Fixed in latest version `1.1.0` of `ngx-order-pipe`.

Thanks @ESimmonds for pointing that out.

**Comment by ESimmonds** [comment]
Thanks @VadimDez
