### ISSUE TITLE
Clarification on deep property sorting.

### ISSUE THREAD

**Issue by CD-UNCC** [VadimDez/ngx-order-pipe#29]
It appears on the page a comma delimited list is specified but I can only see a period separated for the example. Either way I cannot seem to sort on a nested property. My code is
```
    <tr *ngFor="let loc of locationsPage | orderBy: order: reverse; let i = index">
                        <td>{{i + 1}}</td>
                        <td>{{loc.customer.customerName}}</td>
```
```
<th (click)="orderBy('customer.customerName')">Customer</th>
```

oderBy() sets the order key in the *ngFor

```
orderBy(order: string) {
        if (order === this.order) {
            this.reverse = !this.reverse;
        } else {
            this.order = order;
            this.reverse = false;
        }
    }
```
I have many nested properties in my table. I need to sort on a few of them. Is this possible using ng2-order-pipe? If so what is incorrect about my code above? Thank you for reading.

**Comment by VadimDez** [comment]
It seems like you're using old package. Try to use `ngx-order-pipe` instead.

**Comment by VadimDez** [comment]
@CD-UNCC any updates? is it working now?
