### ISSUE TITLE
Reordering during click

### ISSUE THREAD

**Issue by Emkacf** [VadimDez/ngx-order-pipe#33]
Hi,

I've implemented the ngx-order-pipe in angular 5 app where I am sorting the table on which rows are clickable to show more data and pipe is reordering the rows on click. May it be angular 5 compatibility issue/bug or I am doing something wrong?

`<ng-container *ngFor="let vdb of vdbs | orderBy: order">'

And my structure looks like that (clicking on row toogle the hidden table with multiple rows):
```
table
  row
    hidden table
  row
    hidden table
```

My sortable field is in main table rows

`order: string = 'content.properties.DOMAIN.__text';`

**Comment by tabirkeland** [comment]
Same issue.  I believe it is due to the pipe being impure, changed in this commit https://github.com/VadimDez/ngx-order-pipe/commit/90216f462ffb92be4e7a0f533265f3e558a4913a

**Comment by MarkusPint** [comment]
Same issue

**Comment by doublecrusader** [comment]
Same issue. Remove pure:false from ngx-order.pipe.js fix the problem for me.

**Comment by VadimDez** [comment]
What version of `ngx-order-pipe` are you using?

**Comment by nosTa1337** [comment]
I had the same problem with the latest version and solved it with @tabirkeland solution. thanks.

**Comment by grobii** [comment]
Same issue using version 2.0.1

**Comment by grobii** [comment]
For me, it's working with version 2.0.1
