### ISSUE TITLE
order sorting issue in asc & dec

### ISSUE THREAD

**Issue by dgpoo** [VadimDez/ngx-order-pipe#34]
Hello,
I have sorted property listing with date price and sqft value
but in sorting by price there is miss order when price value in differnt number of digit:
like $1,100,000 is showing low value than $299,000
i parsed it into integer number also
https://drive.google.com/file/d/1qdVkL4neLhz-McGBe5klc8iaV73jsn80/view
how can i resolved it?
Thanx.

**Comment by desaishardul** [comment]
Any updates for this issue?
It is sorting based on ascii number. Can we ignore sorting based on ASCII?

**Comment by dgpoo** [comment]
hello,
any update on this?

**Comment by VadimDez** [comment]
You can now use your own custom `comparator` for such cases. See [documentation](https://github.com/VadimDez/ngx-order-pipe/blob/master/README.md).

**Comment by dgpoo** [comment]
Thank you @VadimDez .can you please provide any i example how we can use comparator function?
