### ISSUE TITLE
The pipe 'orderBy' could not be found

### ISSUE THREAD

**Issue by manuvalentim** [VadimDez/ngx-order-pipe#37]
My application is experiencing the following error: _The pipe 'orderBy' could not be found_

` <ion-item *ngFor="let city of availableCities | orderBy:  'city.name'; let index_city = index">`

**Comment by VadimDez** [comment]
Double check how your imported this module.

**Comment by VadimDez** [comment]
Closing, no feedback.

**Comment by alobban** [comment]
Receiving this error as well.

    // app.module
    import { OrderModule } from 'ngx-order-pipe';

    imports: [ ... , OrderModule ];

Was there any other configurations not listed in the instructions?

**Comment by ld-gary** [comment]
Same here, imported same as comment above...
