### ISSUE TITLE
Order issue on load more items.

### ISSUE THREAD

**Issue by dgpoo** [VadimDez/ngx-order-pipe#38]
I am loading 30 items and i can sort it fine.
But if i am loading more  30 items into existance data without page reload then merged new data and old data should sort. 
how i can re-init sort without page reload ?

**Comment by VadimDez** [comment]
What version of `ngx-order-pipe` are you using?

**Comment by dgpoo** [comment]
it is "ng2-order-pipe": "^0.1.5",

**Comment by dgpoo** [comment]
@VadimDez 
Now  i have updated to "ngx-order-pipe": "^1.1.1",

**Comment by VadimDez** [comment]
let me know if the latest version of `ngx-order-pipe` fixes your problem, so that i can close this issue.

**Comment by dgpoo** [comment]
@VadimDez 
no still getting same issue

**Comment by VadimDez** [comment]
can you show me your code?

**Comment by dgpoo** [comment]
[listing.zip](https://github.com/VadimDez/ngx-order-pipe/files/1574848/listing.zip)

i have uploaded above zip file please check it

**Comment by dgpoo** [comment]
@VadimDez 
there much line of code in that 
html file 
line no : 736
line no : 660
-------------------
ts file 
line no : 610
line no : 403

**Comment by VadimDez** [comment]
Have you completely replaced `ng2-order-pipe` with `ngx-order-pipe`? Imported `OrderModule` module?
Pushing to the array you are sorting in the view should actually work (tried myself).

**Comment by dgpoo** [comment]
Awsome it is working now,it is working now!!
please answer me on this issue which i updated last one how can i use compartor using example 
then this plugin works perfect for me
https://github.com/VadimDez/ngx-order-pipe/issues/34
