### ISSUE TITLE
Disable Sorting on a click

### ISSUE THREAD

**Issue by giripradip** [VadimDez/ngx-order-pipe#40]
I am using angular5 and I am sorting an array of objects using ngx-order-pipe for a table data. But data is again sorting when clicking on the table row. how to disable the sorting with a click?

**Comment by VadimDez** [comment]
Are you modifying any item of the list you're sorting on click? If so - that will trigger sorting.

**Comment by giripradip** [comment]
Nope, i am not modifying but i am getting the id of the item that i clicked.

**Comment by nicolashedoire** [comment]
Same problem when i click on the <thead><tr> element... , that trigger sorting, how to solve this bug ?

**Comment by giripradip** [comment]
I am not using this pipe techniques for sorting. In angular, while scrolling the long list change detection event will be triggered. An angular pipe runs its functionality(in this case sorting) on each change detection event. That's why is it flickering while clicking or scrolling also. I am using another technique suggested by many angular developers. That is you can write your sorting logic in component logic itself.

**Comment by VadimDez** [comment]
https://github.com/VadimDez/ngx-order-pipe#use-orderpipe-in-the-component

**Comment by VadimDez** [comment]
Could someone test this issue with version `2.0.0`?
