### ISSUE TITLE
Error using reverse (ExpressionChangedAfterItHasBeenCheckedError)

### ISSUE THREAD

**Issue by erperejildo** [VadimDez/ngx-order-pipe#47]
`  <ion-card *ngFor="let team of gameProvider.game.teams | orderBy: 'team.points':true; let i = index">`

> ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'Team 2'. Current value: 'Team 1'.

These values are in `team.title`. The content inside the html is empty, I'm not displaying anything yet

**Comment by VadimDez** [comment]
Could you show how `gameProvider.game.teams` looks like?

**Comment by erperejildo** [comment]
<img width="189" alt="screen shot 2018-02-11 at 18 06 46" src="https://user-images.githubusercontent.com/5629919/36076602-5acfda74-0f56-11e8-9e40-b98ab2a49c8f.png">

**Comment by VadimDez** [comment]
First of all doing `orderBy: 'team.points'` won't work anyways, try:
```html
<div *ngFor="let team of gameProvider.game.teams | orderBy: 'points': true">
  {{ team | json }}
</div>
```

**Comment by erperejildo** [comment]
I also tried that but same error.

Using Angular 5 with Ionic 3 if that matters

**Comment by erperejildo** [comment]
@VadimDez any update on this?

**Comment by erperejildo** [comment]
Solved using this way:
```
import { ChangeDetectorRef } from '@angular/core';

constructor(private cdRef:ChangeDetectorRef) {
  }

ngAfterViewInit() {
    this.teams = this.gameProvider.game.teams;
    this.cdRef.detectChanges();
  }
```

`<ion-card *ngFor="let team of teams | orderBy: 'points':true; let i = index">`
