### ISSUE TITLE
OrderBy boolean value

### ISSUE THREAD

**Issue by AcePetrucci** [VadimDez/ngx-order-pipe#50]
Hi!
I need to sort a data grid, but it contains a column which is filled with boolean value instead of strings or numbers. For now the data is being sorted like strings and false comes first when using the pipe, so for the time being I set up the column to be always reversed, but this is not the best approach, of course. 
Is there any way to change the pipe to sort boolean values?

**Comment by rafa-as** [comment]
Same here

**Comment by rafa-as** [comment]
@VadimDez this issue should be closed?
