### ISSUE TITLE
The pipe 'orderBy' could not be found

### ISSUE THREAD

**Issue by Guru992** [VadimDez/ngx-order-pipe#51]
First of all thank you for great work with pipe, I would love to use it, but I have an error "The pipe 'orderBy' could not be found". I've tried to do this with your ngx-order-pipe example, but it's not working. Order Module is imported in app.module.ts. My code:

html:  
```
`<tr *ngFor="let rider of pgee2017 | orderBy: order; let i = index">`
<td> {{rider.MSC}} </td>
<td> {{rider.ZAWODNIK}} </td>
<td> {{rider.KLUB}} </td>
```

appComponent:
```
import { Component, OnInit } from '@angular/core';
import { Rider } from "../riders/rider";
import { Danepgee2017Service } from '../../danepgee2017.service';
import { OrderPipe } from 'ngx-order-pipe';

@Component({
  selector: 'gs-pgee2017-stats',
  templateUrl: './pgee2017-stats.component.html',
  styleUrls: ['./pgee2017-stats.component.less'],
})
export class Pgee2017StatsComponent {
pgee2017: Array<any>;
order: string ='msc';
reverse: boolean = false;
  constructor(private _danePgee2017Service: Danepgee2017Service,
    private orderPipe: OrderPipe) 
  {
    
  	this._danePgee2017Service.getPgee2017().subscribe(response => this.pgee2017 = response);
    console.log(this.orderPipe.transform(this._danePgee2017Service, this.order));
}

    setOrder(value: string) {
    if (this.order === value) {
      this.reverse = !this.reverse;
    }
    this.order = value;
}
}
```

I would be grateful for help. Cheers.

**Comment by VadimDez** [comment]
What version of `ngx-order-pipe` are you using?

**Comment by Guru992** [comment]
1.2.1

**Comment by VadimDez** [comment]
I'm confused, why would you pass a `service`?
```typescript
console.log(this.orderPipe.transform(this._danePgee2017Service, this.order));
```
If you comment this line out, does it show you the same error?


Take a look at the example project:
https://stackblitz.com/edit/angular-nck6db?file=app%2Fapp.component.ts

**Comment by Guru992** [comment]
I change my appComponent to something close to your example, but know i have an error: "Cannot read property 'slice' of undefined":

```
import { Component, OnInit } from '@angular/core';
import { Rider } from "../riders/rider";
import { Danepgee2017Service } from '../../danepgee2017.service';
import { OrderPipe } from 'ngx-order-pipe';

@Component({
  selector: 'gs-pgee2017-stats',
  templateUrl: './pgee2017-stats.component.html',
  styleUrls: ['./pgee2017-stats.component.less'],
})
export class Pgee2017StatsComponent {
pgee2017: Array<any>;
result: number[];
  constructor(private _danePgee2017Service: Danepgee2017Service,
    private orderPipe: OrderPipe) 
  {
this._danePgee2017Service.getPgee2017().subscribe(response => this.pgee2017 = response);
let copy = this.pgee2017.slice();
this.result = orderPipe.transform(copy, 'msc');
}
```

**Comment by VadimDez** [comment]
i've released new version `2.0.0`, please update.
I as well updated example for the new version:
https://stackblitz.com/edit/angular-nck6db?file=app%2Fapp.component.ts

In order to make it work change your code to:
```typescript
this._danePgee2017Service.getPgee2017().subscribe((response) => {
  this.pgee2017 = orderPipe.transform(response, 'msc');
});
```

**Comment by Guru992** [comment]
Great! Works good now. Thank you! I have one additional question: in 'msc" column I have numbers from 1 to 55 (this is place in classification) and string "ns" which means "unclassified". When I try to sort it, column goes crazy and I receive different order after every single click. Starting position is always the same, but not good, because after 32 I have: 34, 35, 36, 37, 38, 39, ns, ns, ..., ns, 33, 40.... Is there any solution to sort it right or this is not possible to mix numbers and strings values?

**Comment by VadimDez** [comment]
Closing this for now, since it's solved for your original issue.

Could you show me how your data looks like and which field should be sorted?
