### ISSUE TITLE
Data is flickering/jumping once loaded.

### ISSUE THREAD

**Issue by SrinivasV18** [VadimDez/ngx-order-pipe#55]
My data is jumping on the iniatial load , i have set order with defualt value. Then it worked but, when i click on some column name. Again values are flickering.

**Comment by tidusjar** [comment]
Same here

**Comment by GrantVisser** [comment]
Fixed for me on 2.0.1

**Comment by SrinivasV18** [comment]
Fixed for me in using 1.0.4. 
I am working on Angular 4.0.

**Comment by bluecaret** [comment]
Not working for me on 2.0.4 but only during production Angular 7 builds.
