### ISSUE TITLE
Problem with reverse option but only with a version built with --env=prod

### ISSUE THREAD

**Issue by calamarico** [VadimDez/ngx-order-pipe#58]
First, thanks for share your good job with this module, it's very useful.

I'm having a problem with the reverse true option only when the app is built with the ```--env=prod``` angular-cli flag. I had other problems with angular-cli with the ```--aot``` flag,

I have implemented a material extension panel and I'm using orderBy pipe in this way:

```<mat-expansion-panel *ngFor="let purpose of purposes | async | searchPurposes:value | orderBy:'level':true"```

In development version it runs ok, no problem. But, as I said, in``` --env=prod```, when I toggle or click in the panel or anything that unleash to angular to compute the pipe, the problem is that the filtered items returned is different at any time that they are returned. If I switch the ```reverse: true``` to false, there is no problem (in any version). 
I can't show at this moment any code because it's a "job work", when I will have time, I will try to do a version for you reproducing this problem. But I thought that maybe you will be interested to know if you have see other problems with the different kind of build versions with angular-cli.

**Comment by rodneicouto** [comment]
I have the same problem. I do know why, but when i do slice() everything work fine. 
```
<mat-expansion-panel *ngFor="let purpose of purposes.slice() | async | searchPurposes:value | orderBy:'level':true"
```

**Comment by MerkulovDev** [comment]
Also have a problem in build\serve --prod
if i'm using array with order params, page is flashing.  when i'm scrolling page, every item in table is 'jumping', 'flashing'... looks like some harlem shake on the page ))

**Comment by calamarico** [comment]
That "jumping" and "flashing" it's the same result as I had, I think you are not doing anything wrong, I think the problem is angular 5 in its "prod version".

**Comment by MerkulovDev** [comment]
Solved by installing new module. ngx-pipes works fine!

**Comment by muliyul** [comment]
We're experiencing the same issue when scrolling and there are even values

```typescript
let items = [{date: '1/1/1990'},{date:'1/1/1990'},{date:'2/1/1990'}]
<tr *ngFor="let s of items | orderBy: 'date'">
```

**Comment by MilindSuryawanshi** [comment]
I am facing same issue:
Using Angular 9, When I clicked on any HTML element on-screen abruptly scrolling/pagination changes.
Also, I used mylist.reverse() in my ng-repeat also used pip for some other requirements.
