### ISSUE TITLE
orderBy not found

### ISSUE THREAD

**Issue by miteshpatekar** [VadimDez/ngx-order-pipe#59]
Hi VadimDez,

Thanks for this tool.

I tried your steps mentioned using version "ngx-order-pipe": "^2.0.1".
also included the module as mentioned, but I get this error-
The orderBy in component.html is not found.

When I use the OrderPipe in component.ts it works and I am able to sort using the line-
this.notifications = this.orderPipe.transform(data, 'title')

only when i use it as - 
<div class="row tablerow" *ngFor="let notification of notifications | orderBy: order:reverse:'case-insensitive'; let i=index" (click)="expandRow(i)">
it says orderBy could not be found.

It seems the html could not find orderPipe module. I also tried importing OrderPipe into main module,
but that didn't work too !

Thanks,
Mitesh

**Comment by arseneoaa** [comment]
I had the same issue and it was because I had imported the OrderModule in my root module app.module.ts and not in the module of the component that was using it.

**Comment by jeroldjoel** [comment]
Still Its not working
