### ISSUE TITLE
Sorting on multiple tables in same page

### ISSUE THREAD

**Issue by SrideviYerneni** [VadimDez/ngx-order-pipe#66]
I would like to have sorting on multiple tables which are in same page. I tried to follow this documentation. When I'm sorting the table 1, table 2 is also getting sorted.How do I implement this on multiple tables separately. ?

`
order: any;
reverse: boolean = false;
  setOrder(value: string) {
    if (this.order === value) {
      console.log(this.order)
      this.reverse = !this.reverse;
    }
    this.order = value;
  }`

Table 1 : 
  <table>
                <thead>
                  <tr>
                    <th (click)="setOrder('Data.name')">Name</th>
                    <th (click)="setOrder('Data.age')">Age</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let Data of collection1 | orderBy: order:reverse:'case-insensitive'">
                    <td class="text-truncate">{{Data.name}}</td>
                    <td class="text-truncate">{{Data.age}}</td>
                  </tr>
                </tbody>
              </table>

Table 2 : 
  <table>
                <thead>
                  <tr>
                    <th (click)="setOrder('PersonData.id')">Id</th>
                    <th (click)="setOrder('PersonData.sport')">Sport</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let PersonData of collection2 | orderBy: order:reverse:'case-insensitive'">
                    <td class="text-truncate">{{PersonData.id}}</td>
                    <td class="text-truncate">{{PersonData.sport}}</td>
                  </tr>
                </tbody>
              </table>

**Comment by VadimDez** [comment]
Can you provide more code?

**Comment by SrideviYerneni** [comment]
Table 1 : 
  <table>
                <thead>
                  <tr>
                    <th (click)="setOrder('Data.name')">Name</th>
                    <th (click)="setOrder('Data.age')">Age</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let Data of collection1 | orderBy: order:reverse:'case-insensitive'">
                    <td class="text-truncate">{{Data.name}}</td>
                    <td class="text-truncate">{{Data.age}}</td>
                  </tr>
                </tbody>
              </table>

Table 2 : 
  <table>
                <thead>
                  <tr>
                    <th (click)="setOrder('PersonData.id')">Id</th>
                    <th (click)="setOrder('PersonData.sport')">Sport</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let PersonData of collection2 | orderBy: order:reverse:'case-insensitive'">
                    <td class="text-truncate">{{PersonData.id}}</td>
                    <td class="text-truncate">{{PersonData.sport}}</td>
                  </tr>
                </tbody>
              </table>

**Comment by SrideviYerneni** [comment]
<thead>
                  <tr>
                    <th (click)="setOrder('Data.name')">Name</th>
                    <th (click)="setOrder('Data.age')">Age</th>
                  </tr>
                </thead>

**Comment by VadimDez** [comment]
To help you i need to see how you're sorting both tables. Provide code for both tables (html) and the part where you set order for both collections as well (ts).

**Comment by SrideviYerneni** [comment]
```
 <table>
                <thead>
                  <tr>
                    <th (click)="setOrder('Data.name')">Name</th>
                    <th (click)="setOrder('Data.age')">Age</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let Data of collection1 | orderBy: order:reverse:'case-insensitive'">
                    <td class="text-truncate">{{Data.name}}</td>
                    <td class="text-truncate">{{Data.age}}</td>
                  </tr>
                </tbody>
              </table>
```

**Comment by SrideviYerneni** [comment]
@VadimDez Hi. Is there any update on this ? Please let me know if you need anything more information.

**Comment by mrpatel15** [comment]
i have multiple sorting in 5 different table <th>, it is working fine, but issues with number by sort, find the attached screenshot,

<img width="234" alt="screen shot 2018-05-08 at 8 17 01 pm" src="https://user-images.githubusercontent.com/11543074/39791058-f5316a9c-52fe-11e8-9faa-70687a6bb496.png">

**Comment by atljoseph** [comment]
I am having the same issue with 2 ngFor's, one being nested inside the other. The inner set's orderBy property or callback (whichever is used) is never called. I can replace the outer orderBy function with the inner one and it is always called. It will take 5 minutes to make a simple example in plunker. I have spent 1 hour debugging to find this ... and this occurs consistently. Please look into this.

**Comment by mauriciogracia** [comment]
In my case I have to ng-fors that are not nested but they share the same sorting options and settings

Here you can see my case with code and with my "solution" which is not ideal
