### ISSUE TITLE
experssion not found in build project

### ISSUE THREAD

**Issue by otmane-ma** [VadimDez/ngx-order-pipe#67]
when i tape commande ng buil --prod

console raise an error like 

ERROR in src\app\layout\setup\setup.component.html(23,54): : Property 'born_sup' does not exist on type 'SetupComponent'

but in env dev it works perfectly.

**Comment by VadimDez** [comment]
i can't see what `ngx-order-pipe` has to do with this. It seems like it's your own code that triggers the issue.

**Comment by itsnotme01** [comment]
Hello, 
It seems I have the same trouble when I try to do this kind of things:

```html
<select id="createMailboxLanguageDropDown" class="form-control"
     [(ngModel)]="fileContent.MailboxLanguage" name="createMailboxLanguageDropDown">
    <option *ngFor="let language of languages | orderBy: language : false : true [value]="language">{{language}}</option>
</select>
```

In this case the order works but the production mode build (ng build --prod) fail with the same error as @otmane-ma 

If I try to add a property languageOrder or language with the value 'language' in my component the order does not work.

Do you have an hint on how to directly sort a string array in the html?

**Comment by itsnotme01** [comment]
Hello again,
After some tests I found a solution for my case (sorting an array of string in an ngFor directly in the html),  I just need to orderBy an empty string like this:

``` html
<select id="createMailboxLanguageDropDown" class="form-control"
    [(ngModel)]="fileContent.MailboxLanguage" name="createMailboxLanguageDropDown">
    <option *ngFor="let language of languages | orderBy: language : false : true [value]="language"{{language}}</option>
</select>
```
