### ISSUE TITLE
Incorrectly Sorts Mixed Strings

### ISSUE THREAD

**Issue by jcmcallister** [VadimDez/ngx-order-pipe#71]
For strings that end in numbers, the sort seems to be incorrect. Consider the following:

Example array of strings: ["host1", "host2", "host20", "host12"] 
Displays: ["host1", "host12", "host2", "host20"]
Expected: ["host1", "host2", "host12", "host20"]

This may be a result of the generalist transform algorithms happening in the Pipe, and may be fixable with the use of an extra comparator function during Pipe setup/consumption in my ngx component.

Figured it would be better to raise this issue overtly, in any case, due to this repo's popularity.

**Comment by marzoukiniz** [comment]
I still have the same issue , any updates ??

**Comment by rafa-as** [comment]
Same here

**Comment by anisabboud** [comment]
To use "natural sorting", you can add this comparator (from https://stackoverflow.com/a/38641281) to your typescript file:
```javascript
comparator = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'}).compare;
```
And then use it in the template (see https://github.com/VadimDez/ngx-order-pipe#usage):
```html
<li *ngFor="let item of array | orderBy: order : false : false : comparator">
```

**Comment by rafa-as** [comment]
@VadimDez some news here?
