### ISSUE TITLE
ngx-order-pipe not working for angular 4

### ISSUE THREAD

**Issue by RahulGaikwad7449** [VadimDez/ngx-order-pipe#73]
As i am using ngx-order-pipe version 1.1.3 for my angular 4 application, but its not working.
may i know is there any other dependent module for angular 4

**Comment by VadimDez** [comment]
Is there any message "shown" In console or anywhere else?
And what exactly doesn't work?

**Comment by CarlosTolenk** [comment]
core.js:1673 ERROR Error: Uncaught (in promise): Error: Template parse errors:
The pipe 'orderBy' could not be found ("

<ul>
        <li *ngFor="let [ERROR ->]item of array | orderBy: order:reverse:'case-insensitive'   ">
                {{ item.name }}
      "): ng:///AppsModule/LoteriaComponent.html@131:24
Error: Template parse errors:
The pipe 'orderBy' could not be found ("

<ul>

**Comment by muliyul** [comment]
I'm getting the same error
