### ISSUE TITLE
Allow to sort also by function return value?

### ISSUE THREAD

**Issue by davidmpaz** [VadimDez/ngx-order-pipe#74]
Hi,

first of all, thanksa lot for this project. I was wondering if it would be possible to add possibility to use a function as field value to use.

Currently we can do: `orderBy: 'name'` or `orderBy: 'account.name'`

My request is to allow this scenario: `orderBy: 'product.getPrice'` where price is a function inside `product`.

thanks in advance,
best regards,
David

**Comment by yanis-git** [comment]
Hello @davidmpaz , 

is this implementation looks good for your ? https://github.com/VadimDez/ngx-order-pipe/pull/79

Kind Regards,

**Comment by VadimDez** [comment]
Released in `2.0.2`
