### ISSUE TITLE
order: null or blank values ​​to be always placed at the bottom of the table

### ISSUE THREAD

**Issue by specchiasoft** [VadimDez/ngx-order-pipe#84]
Please I would like the **null or blank values  ​​to be always placed at the bottom of the table** and the other lines always at the beginning ordered by asc or desc.

For example if i modify this  [https://stackblitz.com/edit/ngx-order-pipe](https://stackblitz.com/edit/ngx-order-pipe) only the first two items and i insert null end blank in number and age columns like: 

> `  collection: any[] = [

    {
      id: 1,
      info: {
        name: 'john',
        number: null,
        age: null
      }
    }, {
      id: 5,
      info: {
        name: 'Mary',
        number: '',
        age: null
      }
    }`
If i click  on Phone Number column i would like Jhon and Mary in the last 2 rows,  same if i click in Age column and the other rows ordered on top , i tryed modify defaultCompare 

>   static defaultCompare(a: any, b: any) {
        //   console.log('\n a: ' + a + '  b: ' + b);
        if (a === b) { return 0;}
        if (a == null && b == null) { return 0; }
        if (a != null && b == null) { return -1; }
        if (a == null && b != null) { return 1; }
        return a > b ? 1 : -1;
    }

but whitout succes . 
Thank you for supporting .

**Comment by akvaliya** [comment]
Any updates on this issue? I am facing the same issue
