### ISSUE TITLE
The pipe 'orderBy' could not be found

### ISSUE THREAD

**Issue by roneilbrews** [VadimDez/ngx-order-pipe#85]
First of all thank you for great work with pipe, I would love to use it, but I have an error "The pipe 'orderBy' could not be found".

 let item of all_qualifiations  
                        | orderBy : order:reverse:'case-insensitive'
                        | paginate: { itemsPerPage: 10, currentPage: p }
                        | filter : Term
                      
                    ">

import { OrderPipe } from 'ngx-order-pipe';
   this.sortedCollection = this.orderPipe.transform(this.all_qualifiations, 'all_qualifiations.Name');

**Comment by lukaVarga** [comment]
Instead of adding `OrderModule` to your AppModule `imports`, try adding `OrderPipe` directly in `declarations` of the AppModule (or `declarations` and `exports` if you wish to add it in a different module)

**Comment by albanocristiano1** [comment]
"The pipe 'orderBy' could not be found"...
Any solution? Thanks

Congratulations for the work. beautiful component 👍
