### ISSUE TITLE
I want order by data by filed with mutiple value

### ISSUE THREAD

**Issue by sumit1203** [VadimDez/ngx-order-pipe#86]

**Comment by mnj01121990** [comment]
VadimDez, multi fields not work(((
`this.indexes = this.orderPipe.transform(this.indexes, ['companyUnitCodeIndex', this.order], this.reverse, true);`

**Comment by VadimDez** [comment]
@mnj01121990 could you also provide `this.indexes` and `this.order` ? Otherwise I can't reproduce your error.
