### ISSUE TITLE
skip collection argument, sort by object itself

### ISSUE THREAD

**Issue by vsmelov** [VadimDez/ngx-order-pipe#89]
I have a list of dates in a string format ```['01SEP2019, '12OCT2019', ...]```, I want to sort them using custom compactor, something like
```
let dt of dates | orderBy : 'NOTHING' : false : false : dateComparator
```
, but I want to use object itself, what should I pass as a first argument?

**Comment by VadimDez** [comment]
Right now there's no feature like this
